import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import nunjucks from 'nunjucks';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const TEMPLATES = path.join(ROOT, 'packages/demo/templates');
const OUT = path.join(ROOT, 'docs');

// PAGES_BASE: '' for custom domain at root, '/repo-name' for GitHub Pages sub-path
const BASE = (process.env.PAGES_BASE ?? '').replace(/\/$/, '');

const env = nunjucks.configure(TEMPLATES, { autoescape: true });

// Icon metadata — generated by scripts/generate-icons.ts + build-icons.ts
const iconsMetaPath = path.join(ROOT, 'packages/icons/dist/icons-meta.json');
const iconsMeta: Array<{ name: string; categories: string[]; tags: string[] }> =
  fs.existsSync(iconsMetaPath)
    ? (JSON.parse(fs.readFileSync(iconsMetaPath, 'utf-8')) as Array<{ name: string; categories: string[]; tags: string[] }>)
    : [];

env.addGlobal('base', BASE);
env.addGlobal('iconsMeta', iconsMeta);
env.addGlobal('iconsCount', iconsMeta.length);
env.addGlobal('nav', [
  { label: 'Getting Started', href: '/getting-started.html' },
  { label: 'Theme', href: '/theme.html' },

  { label: 'Icons', href: '/icons.html' },

  { section: true, label: 'Primitives' },
  { label: 'Button', href: '/components/button.html' },
  { label: 'Icon Button', href: '/components/icon-button.html' },
  { label: 'Typography', href: '/components/typography.html' },
  { label: 'Paper', href: '/components/paper.html' },
  { label: 'Box', href: '/components/box.html' },
  { label: 'Container', href: '/components/container.html' },
  { label: 'Stack', href: '/components/stack.html' },
  { label: 'Grid', href: '/components/grid.html' },
  { label: 'Divider', href: '/components/divider.html' },
  { label: 'Icon', href: '/components/icon.html' },

  { section: true, label: 'Forms' },
  { label: 'TextField', href: '/components/text-field.html' },
  { label: 'Select', href: '/components/select.html' },
  { label: 'Checkbox', href: '/components/checkbox.html' },
  { label: 'Radio', href: '/components/radio.html' },
  { label: 'Switch', href: '/components/switch.html' },

  { section: true, label: 'Data Display' },
  { label: 'Avatar', href: '/components/avatar.html' },
  { label: 'Badge', href: '/components/badge.html' },
  { label: 'Chip', href: '/components/chip.html' },
  { label: 'List', href: '/components/list.html' },
  { label: 'Table', href: '/components/table.html' },
  { label: 'Tooltip', href: '/components/tooltip.html' },

  { section: true, label: 'Feedback' },
  { label: 'Alert', href: '/components/alert.html' },
  { label: 'Snackbar', href: '/components/snackbar.html' },
  { label: 'Dialog', href: '/components/dialog.html' },
  { label: 'Backdrop', href: '/components/backdrop.html' },
  { label: 'Circular Progress', href: '/components/circular-progress.html' },
  { label: 'Linear Progress', href: '/components/linear-progress.html' },
  { label: 'Skeleton', href: '/components/skeleton.html' },

  { section: true, label: 'Surfaces' },
  { label: 'Card', href: '/components/card.html' },
  { label: 'Accordion', href: '/components/accordion.html' },

  { section: true, label: 'Navigation' },
  { label: 'App Bar', href: '/components/app-bar.html' },
  { label: 'Tabs', href: '/components/tabs.html' },
  { label: 'Drawer', href: '/components/drawer.html' },
  { label: 'Menu', href: '/components/menu.html' },
  { label: 'Breadcrumbs', href: '/components/breadcrumbs.html' },
  { label: 'Pagination', href: '/components/pagination.html' },
  { label: 'Bottom Navigation', href: '/components/bottom-navigation.html' },
  
  { section: true, label: 'Advanced' },
  { label: 'Slider', href: '/components/slider.html' },
  { label: 'Rating', href: '/components/rating.html' },
  { label: 'Autocomplete', href: '/components/autocomplete.html' },
  { label: 'Stepper', href: '/components/stepper.html' },
  { label: 'Speed Dial', href: '/components/speed-dial.html' },
  { label: 'Modal', href: '/components/modal.html' },
  { label: 'Popover / Popper', href: '/components/popover.html' },
  { label: 'Transitions', href: '/components/transitions.html' },

]);

function copyDir(src: string, dest: string): void {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

function findTemplates(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return findTemplates(full);
    if (entry.isFile() && entry.name.endsWith('.njk') && !entry.name.startsWith('_')) return [full];
    return [];
  });
}

console.log(`Building demo → ${OUT}  (base="${BASE}")`);
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

let ok = 0;
let fail = 0;
for (const templatePath of findTemplates(TEMPLATES)) {
  const rel = path.relative(TEMPLATES, templatePath);
  const urlPath = '/' + rel.replace(/\.njk$/, '.html').replace(/\\/g, '/');
  const currentPath = urlPath === '/index.html' ? '/' : urlPath;

  const outPath = path.join(OUT, rel.replace(/\.njk$/, '.html'));
  fs.mkdirSync(path.dirname(outPath), { recursive: true });

  try {
    const html = nunjucks.render(rel, { currentPath });
    fs.writeFileSync(outPath, html, 'utf8');
    ok++;
  } catch (e) {
    console.error(`  ✗ ${rel}:`, e);
    fail++;
  }
}
console.log(`  ✓ ${ok} pages rendered${fail ? `  ✗ ${fail} failed` : ''}`);

copyDir(path.join(ROOT, 'packages/demo/shared'), path.join(OUT, 'shared'));
console.log('  ✓ shared/');

copyDir(path.join(ROOT, 'packages/demo/public'), path.join(OUT, 'public'));
console.log('  ✓ public/');

copyDir(path.join(ROOT, 'packages/core/dist'), path.join(OUT, 'dist'));
console.log('  ✓ dist/');

// Icons IIFE — optional, only copied if the icons package has been built
const iconsIife = path.join(ROOT, 'packages/icons/dist/materialelements-icons.min.js');
if (fs.existsSync(iconsIife)) {
  fs.copyFileSync(iconsIife, path.join(OUT, 'dist/materialelements-icons.min.js'));
  console.log('  ✓ dist/materialelements-icons.min.js');
}

fs.writeFileSync(path.join(OUT, '.nojekyll'), '');

if (process.env.CNAME) {
  fs.writeFileSync(path.join(OUT, 'CNAME'), process.env.CNAME.trim());
  console.log(`  ✓ CNAME → ${process.env.CNAME.trim()}`);
}

console.log('Done.');
